### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by uliaLiao** [uliaLiao/dsci-310-group-07-pkg#4]
- [x] be named the same as your group project repositry, with the addition of -pkg at the end.

- [x] contain at least 3 or 4 useful functions that handle errors gracefully (you already wrote these - you need to now copy them from your analysis repository to the software package repository)

- [x] be well documented (use the three level of package documentation we learned about in class: function/reference docs, vignette/tutorials docs, and high-level package website docs). **Vignette docs not running and pkgdown:((((((((((((((**

- [x] have unit and integration tests (you already wrote these - you need to now copy them from your analysis repository to the software package repository)

- [x] use GitHub actions for continuous integration to run your tests, and continuous deployment to render your package documentation. **Check release missing**.

- [x] have a badge for a code coverage

- [x] have a README that describes your package from a high-level, including where it sits in the package ecosystem for the language you chose to write it in chose (i.e., what other similar packages exist and how do they differ)

- [x] have a Software Licence that describes how you will permit others to use your work

- [x] have a code of conduct document that describes behavioural expectations of team interactions

- [x]  have a contributions document that outlines how the team will work together (expected workflow practices)
